[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "apartmentprices"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "seleniumbase>=4.51.12",
    "ruff>=0.16.2",
    "ipykernel>=7.3.0",
    "pandas>=3.0.5",
    "seaborn>=0.13.2",
    "statsmodels>=0.15.0",
]

[tool.setuptools.packages.find]
where = ["src"]
